### ISSUE TITLE
Converting JsonData array to .NET

### ISSUE THREAD

**Issue by JVimes** [LitJSON/litjson#103]
Is there a simple way to get a .NET array/enumerable/list/collection of strings from a JsonData array of strings? I want to use the non-generic ToObject(). It seems like there should be a simpler way than looping.

{JsonData array} has IEnumerable and {JsonData string} can be cast to string, so `Cast<string>()` should work. But it throws an exception, "Unable to cast object of type 'LitJson.JsonData' to type 'System.String'". Here's [a .NET fiddle showing my attempt](https://dotnetfiddle.net/9xIcHn).

**Comment by ryanvs** [comment]
The `Cast<string>` method is [bound at compile time](https://stackoverflow.com/a/13316745/29762) and performs a generic cast and doesn't know about [implicit and explicit operators](https://stackoverflow.com/questions/808725/why-does-a-linq-castt-operation-fail-when-i-have-an-implicit-cast-defined). You can do this though:
```C#
    var tracksAsList = rawTracks.Cast<JsonData>()
                                .Select(x => (string)x)
                                .ToList(); // List<string>
```
You cannot use `Select` directly on `rawTracks` because the Select extension uses `IEnumerable<T>`, so the `Cast<JsonData>` converts `IEnumerable` to `IEnumerable<JsonData>` (see this [link](https://stackoverflow.com/questions/812673/convert-cast-ienumerable-to-ienumerablet)) so you can call `Select`. Here is a [forked .NET fiddle](https://dotnetfiddle.net/hf7Pf5).

It might be worthwhile implementing `IEnumerable<JsonData>` or `IList<JsonData>` on `IJsonWrapper` and `JsonData` (and internally call `EnsureList`) to avoid the first `Cast<JsonData>`.

Note, I haven't used LitJSON, but I was just browsing this repository as I was looking into the possibility of using [LitJSON in a SQL CLR Function](https://stackoverflow.com/a/42179401/29762) and I was browsing the issues.

**Comment by JVimes** [comment]
Thanks, Ryan. I didn't know that about Cast<>(). Just curious, do you know a reason to use non-generic IEnumerable for something like this? I don't run into it often.

I stopped using LitJSON because, if I remember right, it didn't seem to support spaces in json attribute names when deserializing to .NET objects.

**Comment by ryanvs** [comment]
The non-generic `IEnumerable` is just a by-product of the non-generic `IList` implementation in `IJsonWrapper`. From my initial look, I would also implement `IList<JsonData>`, however there is no generic version of [IOrderedDictionary](https://stackoverflow.com/questions/2629027/no-generic-implementation-of-ordereddictionary).

Good to know about the possible deserializing issue. Thanks.
