### ISSUE TITLE
Mature/Fixed/Centralized fork?

### ISSUE THREAD

**Issue by sisso** [LitJSON/litjson#46]
Appears that this original project is "dead". I saw many forks with fixing and improved stuff. Which one should be considered a centralized / mature one?

If none, we have a candidate to help to organize and merge the pull requests?

**Comment by lbv** [comment]
Hello,

Thank you for asking this. The reality is that, although I'd like to keep maintaining this piece of software I wrote many years ago, I don't see that happening any time soon.

If there is someone who actively uses LitJSON (or a stable fork) and wants to take the duties of maintainer, I'd happily arrange the logistics from my side :).

To make it more explicit, to the interested parties reading this: feel free to recommend a candidate for this role in here.

Thanks!

**Comment by sisso** [comment]
Good news, you are alive. Yeah, I understand. But It is a good and simple library for c#, the work must go on. 

With +100 forks is dificult to choose one. 

I have elected https://github.com/mviranyi/litjson as my main branch. It is functional for my needs. 

Congratulation @mviranyi

:P

**Comment by mviranyi** [comment]
Hi Sisso

thanks for choosing my fork as main branch .. @ o @ I feel honored *deepbowing*
I'm still using LitJson for my projects (including and mainly for Unity3D). Actually it is still the most convenient implementation I've used so far (although I didn't do any performance checks).

Shortly about the plans with LitJson:

Every time I stumble upon a not implemented type from the UnityEngine namespace I add it. From my side it is currently maintained on demand. I'll of course handle merge request if any is dropped onto me. (Sidenote: the origin from my fork from Happy-Tuesday doesn't seem to be maintained anymore..)

I will slowly turn the project into a Mono Develop solution-ed one, when I've the time. Although I don't want to force this dependency.

And that's it basically.


Have fun using LitJson! ;)

**Comment by ht-Friedrich** [comment]
@mviranyi : The original fork from Happy Tuesday is no longer maintained. We dont use LitJson anylonger. It will stay for convinience for a while.

**Comment by lbv** [comment]
A few thoughts..

First of all, I'm very glad to see LitJSON being used in the wild, and to see people interested in its future and on improving it. My thanks to all of you, my friends.

Now, I don't think "With +100 forks is dificult to choose one" is very accurate. As with any project on GitHub, the number of forks here is not necessarily indicative on the actual number of serious efforts to maintain a viable alternative of the software. I think the exercise of googling "LitJSON" (maybe adding a few other keywords) should reveal that the number of forks currently backed by responsive developers and being used by a good number of users is not in the order of hundreds.

That being said, my idea is to keep this issue open here for a few days, maybe a couple of weeks, to see if more interested parties come across it, and we as a group can take the best decision as to who can carry on with this project.

As someone who saw the birth of this project, I have a short wishlist of things I'd like to see in LitJSON going forward, no matter who takes over ownership. I'll write it down:

- I'd like to see LitJSON as a lean, fast library. Let's keep it small and minimize the fuss to install/configure it, and maximize the fun in using it (by that I mean the practical use of its API).
- I hope it stays public domain, although anyone can do as it pleases, including changing its license if that's what they want—btw, I'm not sure how easy or practical that would be, it's just a hypothetical, please let's not talk about this anymore :).
- I realize many people use LitJSON in association with Unity, so I can see how it would be useful to include Unity-specific related things with it. However, I hope those things are implemented in such a way that it doesn't alter LitJSON's nature, being the small, simple library it is now. So, I'd like that at its core it's still small and agnostic to any external software (be it Unity or anything else), but it could include optional extras if that makes it easier to use in common scenarios.
- Related to the previous point, it'd be nice to provide the scaffolding necessary to build LitJSON in different environments (like MonoDevelop, Visual Studio, GNU make, etc.), but again, it should be optional, and the project should not be tied to any particular building mechanism as to make it impossible to maintain unless people use a specific tool to build it.

That's it for now, I think.

Thanks again to everyone, and particularly to @mviranyi, who seems interested in the job (I hope I'm not misunderstanding, let me know otherwise).

**Comment by mviranyi** [comment]
Hello Leonardo

nice seeing you as an elder developer from LitJson commenting. 
Let me shortly give peace to your mind ..

-----

* I'd like to see LitJSON as a lean, fast library. Let's keep it small and minimize the fuss to install/configure it, and maximize the fun in using it (by that I mean the practical use of its API).

  *My plan isn't to rewrite or alter LitJson's approach, systematics, API nor its nature. The primary goal is extending LitJson so it can be utilized with Unity3D easily. Since LitJson is so small and lean and thus easy to implement and use I see it very well fitting with Unity3D's philosophy.*

* I hope it stays public domain, although anyone can do as it pleases, including changing its license if that's what they want—btw, I'm not sure how easy or practical that would be, it's just a hypothetical, please let's not talk about this anymore :).

  *Don't give up hope. That is my intention all along. I've already dealt with my current work place's legal department in order to contribute back to LitJson. All my efforts made during my every day work will be brought back into the public domain. Double promise!*

* I realize many people use LitJSON in association with Unity, so I can see how it would be useful to include Unity-specific related things with it. However, I hope those things are implemented in such a way that it doesn't alter LitJSON's nature, being the small, simple library it is now. So, I'd like that at its core it's still small and agnostic to any external software (be it Unity or anything else), but it could include optional extras if that makes it easier to use in common scenarios.

  *I already thought of this and kept LitJson configurable through preprocessor defines. If UNITY3D isn't defined, the whole Unity3D related types and implementations won't be in the deployment. By default that should and will be the case.*

* Related to the previous point, it'd be nice to provide the scaffolding necessary to build LitJSON in different environments (like MonoDevelop, Visual Studio, GNU make, etc.), but again, it should be optional, and the project should not be tied to any particular building mechanism as to make it impossible to maintain unless people use a specific tool to build it.

  *Understood. Instead of shifting the deployment to an IDE I'm going to extend the readme and build pipeline accordingly.*

-----

Let us see how progress goes.  
Currently I'm not planning to provide stable public deployments nor extending the test cases (although I should). I thought of using LitJson library inside a Unity3D editor toolset provided on the AssetStore. For this I'd start with proper releases including LitJson libraries. Unfortunately some pressing projects prohibit me from following that thought.

Although it seems I'm only interested in extending LitJson towards the Unity3D engine, I'm also using it inside general C# projects. So keeping its generality is as well a goal of mine.

Great weekend to all of you!

**Comment by devlead** [comment]
A LitJSON organization has now been formed and I've stepped in as maintainer. I'll try to get some CI/CD going and will post that try to go through the PRs & issues.

I've already ported to .NET Core and UWP in another fork and will try to refactoring in that in this repo.
