### ISSUE TITLE
Support for .NET Framework 2.0

### ISSUE THREAD

**Issue by immitev** [LitJSON/litjson#72]
Version ` 0.9.0.0` of the library offered a .NET 2.0 build, while currently .NET 3.5 seems to be the oldest .NET Framework supported. Is there a reason to drop support for .NET 2.0 (e.g Json.NET still supports .NET 2.0)?

**Comment by devlead** [comment]
@immitev no reason other than what's setup in the CI tooling, should be possible.

.NET 2.0 isn't supported by Microsoft anymore and they recommend .NET 3.5 as an in-place upgrade, 3.5 is supported because it comes with some versions of SQL Server.

That said, with the right targeting pack we should theoretically be able to support 2.0 even when using the .NET CLI, don't think there's anything in the code, that's not compileable under 2.0, and happily review contribution to add that support.

**Comment by devlead** [comment]
fixed by #73

**Comment by devlead** [comment]
@immitev  v0.12.0 is now available on nuget, thanks for for your contribution.
https://www.nuget.org/packages/LitJson/0.12.0
![image](https://user-images.githubusercontent.com/1647294/35328543-008f13fc-00fd-11e8-9bcd-b3d254e068cb.png)
